layout_spectrum: 1
color:
  saturation: 0.009129935
  lightness: 0
  brandStrength: 1
  brandColors:
    - '#CECEC7'
    - '#0D0D0D'
    - '#A2A49A'
    - '#7F817E'
    - '#421F02'
  rhythmicContrast: 0.1766917
typography_spectrum: 0.7867884
name: Uniregistry
